import type { IndustryCategory, IndustryMeta } from '../types';

export const INDUSTRY_CATEGORIES: Record<IndustryCategory, IndustryMeta> = {
  auto: {
    id: 'auto',
    label: '✦ Auto-Detect',
    shortLabel: 'Auto',
    icon: '✦',
    biasTerms: 'equipment machine tool instrument',
    sampleTerms: [
      'Excavator',
      'Oscilloscope',
      'Microscope',
      'Centrifuge',
      '3D printer',
      'Multimeter',
      'Wind turbine',
      'Lathe',
    ],
  },
  construction: {
    id: 'construction',
    label: '🏗️ Construction & Heavy Equipment',
    shortLabel: 'Construction',
    icon: '🏗️',
    biasTerms: 'construction heavy equipment machinery machine vehicle',
    sampleTerms: [
      'Excavator',
      'Bulldozer',
      'Crane machine',
      'Concrete mixer',
      'Wheel loader',
      'Dump truck',
      'Road roller',
      'Backhoe',
    ],
  },
  manufacturing: {
    id: 'manufacturing',
    label: '🏭 Manufacturing & Industrial',
    shortLabel: 'Manufacturing',
    icon: '🏭',
    biasTerms: 'manufacturing industrial machinery factory machine tool',
    sampleTerms: [
      'Lathe',
      'CNC machine',
      'Injection molding',
      'Industrial robot',
      'Conveyor belt',
      'Press brake',
      'Laser cutter',
      'Welding machine',
    ],
  },
  laboratory: {
    id: 'laboratory',
    label: '🔬 Laboratory & Scientific',
    shortLabel: 'Laboratory',
    icon: '🔬',
    biasTerms: 'laboratory scientific instrument science chemistry biology',
    sampleTerms: [
      'Microscope',
      'Centrifuge',
      'Spectrophotometer',
      'Autoclave',
      'Pipette',
      'Chromatography',
      'Incubator',
      'Fume hood',
    ],
  },
  electrical: {
    id: 'electrical',
    label: '⚡ Electrical & Tools',
    shortLabel: 'Electrical',
    icon: '⚡',
    biasTerms: 'electrical electronics electronic test tool instrument power',
    sampleTerms: [
      'Oscilloscope',
      'Multimeter',
      'Signal generator',
      'Soldering station',
      'Power supply',
      'Transformer',
      'Spectrum analyzer',
      'Logic analyzer',
    ],
  },
};

export const INDUSTRY_KEYS: IndustryCategory[] = [
  'auto',
  'construction',
  'manufacturing',
  'laboratory',
  'electrical',
];
